; -----------------------------------------------------------------------------
;
;   Title screen test
;   * Sets the screen to solid blocks and colors them with the game title
;
;   NOTE: This was generated by a python program and is about as big as it can
;         be!  I didn't want to optimize or compress it at all based on the
;         requirements given, but obviously this could be a LOT smaller!
; 
;   author: Jeremy Stuart
; -----------------------------------------------------------------------------

; GLOBAL VARIABLES
CLOCK_TICKS = $0001

; IMPORTANT MEMORY LOCATIONS
COLOR_ADDR = $9600
SCREEN_ADDR = $1e00

; SCREEN SIZE RELATED MEMORY LOCATIONS
CENTERING_ADDR = $9001          ; stores the screen centering values
COLUMNS_ADDR = $9002            ; stores the number of columns on screen
ROWS_ADDR = $9003               ; stores the number of rows on screen

    processor 6502
    org $1001
    
    dc.w stubend ; define a constant to be address @ stubend
    dc.w 12345 
    dc.b $9e, "4109", 0
stubend
    dc.w 0

; DEF SCREEN_DIM
; change the screen size to 16x16
screen_dim
    lda     #$90                ; bit pattern 10010000, lower 6 bits = 16
    sta     COLUMNS_ADDR        ; store in columns addr to set screen to 16 cols

    lda     #$20                ; bit pattern 00101000, bits 1to6 = 16
    sta     ROWS_ADDR           ; store in rows addr to set screen to 16 rows

    lda     #$09                ; i don't know what i'm doing
    sta     $9000               ; horizontal screen centering

    lda     #$20                ; i don't know why this value works but it does
	sta     CENTERING_ADDR      ; vertical screen centering
; END SCREEN_DIM

; SET SCREEN BORDER TO BLACK
    lda     #24                 ; white screen with a black border
    sta     $900F               ; set screen border color

    ldx     #0                  ; set x to zero
; draw title screen
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #4                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #146            ; R
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #149            ; U
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color HERE
    sta     $9600,x
    lda     #142            ; N
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #148            ; T
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #137            ; I
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #141            ; M
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #133            ; E
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224           ; SPACE
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #148            ; T
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #133            ; E
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #146            ; R
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #146            ; R
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #143            ; O
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #146            ; R
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; SPACE
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; SPACE
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #178            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #176            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #178            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #178            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx
    
    lda     #0                ; set the color
    sta     $9600,x
    lda     #224            ; fill the space with a block
    sta     $1e00,x
    inx

; END TITLE SCREEN

; loop to display the screen
loop
    nop
    jmp loop
