%.prg:
			dasm $< -o$@ -l$*.lst

all:			charprint.prg indirect_ex.prg screenfill.prg custom_char.prg custom_char2.prg fall.prg vertical-animation-loop.prg simple-fall.prg falling-block.prg

charprint.prg:			charprint.s
indirect_ex.prg: 		indirect_ex.s
screenfill.prg: 		screenfill.s
custom_char.prg:		custom_char.s
custom_char2.prg:		custom_char2.s
fall.prg:			fall.s
vertical-animation-loop.prg:	vertical-animation-loop.s
simple-fall.prg:		simple-fall.s
falling-block.prg:		falling-block.s
