name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download DASM
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'dasm-assembler/dasm'
          file: 'dasm-2.20.14.1-linux-x64.tar.gz'
          target: 'dasm/dasm.tar.gz'

      - name: Check file structure
        run: |
          ls -lR

      - name: Decompress DASM
        run: |
          tar -xvf dasm/dasm.tar.gz --directory dasm

      - name: Move DASM to /usr/bin to use with Make
        run: sudo cp ./dasm/dasm /usr/bin/dasm

      - name: Checkout zzza repo
        uses: actions/checkout@v4

      - name: Make zzza
        working-directory: /home/runner/work/zzza/zzza/zzza
        run: |
          pwd
          ls -la
          make
                          
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            /home/runner/work/zzza/zzza/zzza/main.prg